id: IC46A8D68
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:53:11+00:00'
last_modified: '2022-06-07T17:57:26.080802+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19009
  title: བོད་ཀྱི་གསོ་རིག་ནད་ཐོག་ལག་ལེན་གྱི་སློབ་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    79C7:
      image_group_id: I8LS19011
      title: ''
      total_pages: 684
      order: 1
      base_file: 79C7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
